"""
Export Manager for generating reports
"""

import logging
from datetime import datetime
from pathlib import Path
import json
import csv

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (SimpleDocTemplate, Table, TableStyle, Paragraph,
                               Spacer, Image as RLImage, PageBreak)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from config.config import EXPORTS_DIR, APP_NAME, ORGANIZATION

logger = logging.getLogger(__name__)

class ExportManager:
    """Manages export of data to various formats"""
    
    def __init__(self):
        self.exports_dir = EXPORTS_DIR
        self.exports_dir.mkdir(parents=True, exist_ok=True)
    
    # ========================================================================
    # PDF EXPORT
    # ========================================================================
    
    def export_match_report_pdf(self, suspect_info, matches, user_info):
        """
        Export match results to PDF report
        
        Args:
            suspect_info (dict): Suspect information
            matches (list): List of match results
            user_info (dict): User who generated report
            
        Returns:
            str: Path to generated PDF
        """
        try:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"match_report_{timestamp}.pdf"
            filepath = self.exports_dir / filename
            
            # Create PDF document
            doc = SimpleDocTemplate(
                str(filepath),
                pagesize=letter,
                rightMargin=0.5*inch,
                leftMargin=0.5*inch,
                topMargin=0.5*inch,
                bottomMargin=0.5*inch
            )
            
            # Container for elements
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#6D8196'),
                spaceAfter=30,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold'
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                textColor=colors.HexColor('#4A4A4A'),
                spaceAfter=12,
                spaceBefore=12,
                fontName='Helvetica-Bold'
            )
            
            # Title
            elements.append(Paragraph(APP_NAME, title_style))
            elements.append(Paragraph("Face Recognition Match Report", styles['Heading2']))
            elements.append(Spacer(1, 0.3*inch))
            
            # Report metadata
            metadata = [
                ['Report Generated:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
                ['Generated By:', user_info.get('full_name', 'Unknown')],
                ['Role:', user_info.get('role', 'Unknown')],
                ['Organization:', ORGANIZATION]
            ]
            
            metadata_table = Table(metadata, colWidths=[2*inch, 4*inch])
            metadata_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#4A4A4A')),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            
            elements.append(metadata_table)
            elements.append(Spacer(1, 0.3*inch))
            
            # Suspect Information
            elements.append(Paragraph("Suspect Information", heading_style))
            
            suspect_data = [
                ['Image Path:', suspect_info.get('image_path', 'N/A')],
                ['Upload Time:', suspect_info.get('timestamp', 'N/A')],
                ['Description:', suspect_info.get('description', 'N/A')]
            ]
            
            suspect_table = Table(suspect_data, colWidths=[2*inch, 4*inch])
            suspect_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            
            elements.append(suspect_table)
            elements.append(Spacer(1, 0.2*inch))
            
            # Suspect image
            if suspect_info.get('image_path') and Path(suspect_info['image_path']).exists():
                try:
                    img = RLImage(suspect_info['image_path'], width=2*inch, height=2*inch)
                    elements.append(img)
                except:
                    pass
            
            elements.append(Spacer(1, 0.3*inch))
            
            # Match Results
            elements.append(Paragraph(f"Match Results ({len(matches)} matches found)", heading_style))
            elements.append(Spacer(1, 0.1*inch))
            
            if matches:
                for idx, match in enumerate(matches, 1):
                    criminal = match['criminal']
                    
                    # Match header
                    match_title = f"Match #{idx} - Similarity: {match['similarity']:.2f}%"
                    elements.append(Paragraph(match_title, styles['Heading3']))
                    
                    # Criminal details
                    criminal_data = [
                        ['Criminal ID:', criminal[1]],
                        ['Name:', criminal[2]],
                        ['Age:', str(criminal[3]) if criminal[3] else 'N/A'],
                        ['Height:', criminal[4] or 'N/A'],
                        ['Status:', criminal[8]],
                        ['Charges:', criminal[6][:100]],
                        ['Case Number:', criminal[9] or 'N/A'],
                        ['Jurisdiction:', criminal[10] or 'N/A'],
                    ]
                    
                    criminal_table = Table(criminal_data, colWidths=[2*inch, 4*inch])
                    criminal_table.setStyle(TableStyle([
                        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                        ('FONTSIZE', (0, 0), (-1, -1), 9),
                        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E8D59E')),
                    ]))
                    
                    elements.append(criminal_table)
                    elements.append(Spacer(1, 0.2*inch))
                    
                    # Confidence assessment
                    confidence = self._get_confidence_level(match['similarity'])
                    confidence_para = Paragraph(
                        f"<b>Confidence Level:</b> {confidence}",
                        styles['Normal']
                    )
                    elements.append(confidence_para)
                    elements.append(Spacer(1, 0.3*inch))
            else:
                elements.append(Paragraph("No matches found in the database.", styles['Normal']))
            
            # Footer
            elements.append(Spacer(1, 0.5*inch))
            footer_style = ParagraphStyle(
                'Footer',
                parent=styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
            elements.append(Paragraph(
                f"This is an official report generated by {APP_NAME}<br/>"
                f"All information is confidential and for authorized personnel only.",
                footer_style
            ))
            
            # Build PDF
            doc.build(elements)
            
            logger.info(f"PDF report generated: {filepath}")
            return str(filepath)
            
        except Exception as e:
            logger.error(f"PDF export error: {e}")
            return None
    
    def export_criminal_list_pdf(self, criminals, user_info):
        """
        Export criminal database to PDF
        
        Args:
            criminals (list): List of criminals
            user_info (dict): User information
            
        Returns:
            str: Path to generated PDF
        """
        try:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"criminal_database_{timestamp}.pdf"
            filepath = self.exports_dir / filename
            
            doc = SimpleDocTemplate(str(filepath), pagesize=A4)
            elements = []
            styles = getSampleStyleSheet()
            
            # Title
            title_style = ParagraphStyle(
                'Title',
                parent=styles['Heading1'],
                fontSize=20,
                textColor=colors.HexColor('#6D8196'),
                alignment=TA_CENTER
            )
            
            elements.append(Paragraph("Criminal Database Report", title_style))
            elements.append(Spacer(1, 0.2*inch))
            
            # Metadata
            metadata = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | " \
                       f"By: {user_info.get('full_name', 'Unknown')} | " \
                       f"Total Records: {len(criminals)}"
            elements.append(Paragraph(metadata, styles['Normal']))
            elements.append(Spacer(1, 0.3*inch))
            
            # Table data
            table_data = [['ID', 'Name', 'Age', 'Status', 'Charges', 'Case #']]
            
            for criminal in criminals:
                table_data.append([
                    criminal[1][:15],  # ID
                    criminal[2][:20],  # Name
                    str(criminal[3]) if criminal[3] else 'N/A',  # Age
                    criminal[8],  # Status
                    criminal[6][:30],  # Charges
                    criminal[9][:15] if criminal[9] else 'N/A'  # Case #
                ])
            
            table = Table(table_data, colWidths=[1*inch, 1.5*inch, 0.6*inch, 0.8*inch, 2*inch, 1*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6D8196')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
            ]))
            
            elements.append(table)
            doc.build(elements)
            
            logger.info(f"Criminal list PDF generated: {filepath}")
            return str(filepath)
            
        except Exception as e:
            logger.error(f"Criminal list PDF export error: {e}")
            return None
    
    # ========================================================================
    # CSV EXPORT
    # ========================================================================
    
    def export_matches_csv(self, matches):
        """Export matches to CSV"""
        try:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"matches_{timestamp}.csv"
            filepath = self.exports_dir / filename
            
            with open(filepath, 'w', newline='', encoding='utf-8') as f:
                fieldnames = ['Criminal_ID', 'Name', 'Similarity', 'Age', 'Height',
                            'Charges', 'Status', 'Case_Number', 'Jurisdiction']
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                
                writer.writeheader()
                for match in matches:
                    criminal = match['criminal']
                    writer.writerow({
                        'Criminal_ID': criminal[1],
                        'Name': criminal[2],
                        'Similarity': f"{match['similarity']:.2f}%",
                        'Age': criminal[3] or 'N/A',
                        'Height': criminal[4] or 'N/A',
                        'Charges': criminal[6],
                        'Status': criminal[8],
                        'Case_Number': criminal[9] or 'N/A',
                        'Jurisdiction': criminal[10] or 'N/A'
                    })
            
            logger.info(f"CSV export generated: {filepath}")
            return str(filepath)
            
        except Exception as e:
            logger.error(f"CSV export error: {e}")
            return None
    
    def export_criminals_csv(self, criminals):
        """Export criminal database to CSV"""
        try:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"criminals_{timestamp}.csv"
            filepath = self.exports_dir / filename
            
            with open(filepath, 'w', newline='', encoding='utf-8') as f:
                fieldnames = ['Criminal_ID', 'Name', 'Age', 'Height', 'Physical_Description',
                            'Charges', 'Status', 'Case_Number', 'Jurisdiction', 'Created_At']
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                
                writer.writeheader()
                for criminal in criminals:
                    writer.writerow({
                        'Criminal_ID': criminal[1],
                        'Name': criminal[2],
                        'Age': criminal[3] or 'N/A',
                        'Height': criminal[4] or 'N/A',
                        'Physical_Description': criminal[5] or 'N/A',
                        'Charges': criminal[6],
                        'Status': criminal[8],
                        'Case_Number': criminal[9] or 'N/A',
                        'Jurisdiction': criminal[10] or 'N/A',
                        'Created_At': criminal[11]
                    })
            
            logger.info(f"Criminal CSV export generated: {filepath}")
            return str(filepath)
            
        except Exception as e:
            logger.error(f"Criminal CSV export error: {e}")
            return None
    
    # ========================================================================
    # JSON EXPORT
    # ========================================================================
    
    def export_matches_json(self, matches):
        """Export matches to JSON"""
        try:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"matches_{timestamp}.json"
            filepath = self.exports_dir / filename
            
            export_data = {
                'export_date': datetime.now().isoformat(),
                'total_matches': len(matches),
                'matches': []
            }
            
            for match in matches:
                criminal = match['criminal']
                export_data['matches'].append({
                    'criminal_id': criminal[1],
                    'name': criminal[2],
                    'similarity': match['similarity'],
                    'age': criminal[3],
                    'height': criminal[4],
                    'charges': criminal[6],
                    'status': criminal[8],
                    'case_number': criminal[9],
                    'jurisdiction': criminal[10]
                })
            
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(export_data, f, indent=4, default=str)
            
            logger.info(f"JSON export generated: {filepath}")
            return str(filepath)
            
        except Exception as e:
            logger.error(f"JSON export error: {e}")
            return None
    
    # ========================================================================
    # HELPER METHODS
    # ========================================================================
    
    def _get_confidence_level(self, similarity):
        """Get confidence level description"""
        if similarity >= 85:
            return "Very High - Strong match"
        elif similarity >= 75:
            return "High - Good match"
        elif similarity >= 65:
            return "Medium - Possible match"
        elif similarity >= 55:
            return "Low - Weak match"
        else:
            return "Very Low - Unlikely match"